import numpy


def LFMap(i,bwt):

    rankChars=['$','A','C','G','T']
    occurences=0    
    checkChar=bwt[i]
    print(checkChar)
    indexOfCheckChar=rankChars.index(checkChar)
    
    for j in range(0,indexOfCheckChar):
        occurences+=bwt.count(rankChars[j])
    #checks occurences of current character before the given index
    slicedBWT=bwt[:i]    
    occurenceOfCurrentChar=slicedBWT.count(checkChar)
   
    return occurences+occurenceOfCurrentChar    
        
        

if __name__ == '__main__':
      
    inputData='AACGTTGTTCGCCAACGATTTAACCCCGCCCCAAATTTTCCGGGGGGGATACCCAACGCGGCTTAAGCTTGACGCACGATACGCTGAATACGATATAAGACCGTTCGAATGTAGGCCCGTTCTAGGGCCCGGCGGGCGGGGATCTAAGCTTCTATTAGTCCTTTGGATCGGGTTAGATTTTTGACAAGAAGTATTGTCAGGCATGAATTGTGGGGATTTCCCGCCACTGTATCCTGAAGGTGCGCGGCTCTAAACGAGCGGAGTGAAGACCTCTCCATTCACGTTTGTGACGCCCTCAACTCTTGGCCGTCTTAGATTTCCCTCGTCACACACGGGGTCCGTAATGTCTAGCTACACGCCGCTTAGTGCTCAAGCAGAGAGTCGCCGTTCGATTATACTCTCGCTGTCTTAGAGACGACAGAGTAGGTCTAATGTCTGGATTTTTTTAGTCATCGCAGCAAGATAGTTGACTGGTTTAAGAAATCCAAAATTGCCTGGAAGCTGCAAATCGCATGATAAGGATTCGAACTTGGCGCGAATCGACCTACACCTGTCATATAATCTCAACTTATTCGACACCATCGATGACTTACCTAAAGCTATACGTGTGACCATTTTTATGGTACTACCTTTATGCAAATAGTTGGCCTACTGCCCCAATCAGCAATACACGCGTCTTACCAAGCTTCGGTCGGTGAAGATGGCATCAGGATCAGAAGGACCTGGACAGTTTCTGATGCTCCAGTAGCTATTTGTTATAATAATCAATCGTTAGAGCATCTCCGCGGATTCAGATCTTAAGTGGTGTTCTGCCGCGGCGGCAAGATAAACTTTGATGTGCCGTGAGACTC$'
    #print(inputData)    
    position=LFMap(607,inputData)
    print(position)