codonTable={
    'GCU':'A', 'GCC':'A', 'GCA':'A', 'GCG':'A',
    'CGU':'R', 'CGC':'R', 'CGA':'R', 'CGG':'R', 'AGA':'R', 'AGG':'R',
    'AAU':'N', 'AAC':'N',
    'GAU':'D', 'GAC':'D',
    'UGU':'C', 'UGC':'C',
    'CAA':'Q', 'CAG':'Q',
    'GAA':'E', 'GAG':'E',
    'GGU':'G', 'GGC':'G', 'GGA':'G', 'GGG':'G',
    'CAU':'H', 'CAC':'H',
    'AUU':'I', 'AUC':'I', 'AUA':'I',
    'AUG':'START',
    'UUA':'L', 'UUG':'L','CUU':'L', 'CUC':'L', 'CUA':'L', 'CUG':'L',
    'AAA':'K', 'AAG':'K',
    'AUG':'M',
    'UUU':'F', 'UUC':'F',
    'CCU':'P', 'CCC':'P', 'CCA':'P', 'CCG':'P',
    'UCU':'S', 'UCC':'S', 'UCA':'S', 'UCG':'S', 'AGU':'S', 'AGC':'S',
    'ACU':'T', 'ACC':'T', 'ACA':'T', 'ACG':'T',
    'UGG':'W',
    'UAU':'Y', 'UAC':'Y',
    'GUU':'V', 'GUC':'V', 'GUA':'V', 'GUG':'V',
    'UAA':'STOP', 'UGA':'STOP', 'UAG':'STOP'
    }
totalCodons=1                
testInput='MAAPPWEMDTGVNLMNCERFTRWCRNSEWGILHTTVQANWICTMTTAHFHSSFFNIVMDNWTPNEWGYEQLVTSIFMVEMLLGQRRKMLQKNRNIVRWRGMVYLTVDKNWNHTFMGKVMWKMWISPMYRNDCYLLCQNICGTFMKWFDIKQCPFHLLVVMFLGVDPLMQNVANAPYTHAPQAFMEWKIGLSYMALPAQGSVNQSCKIPQTMECHDDRDYGKVSEIFHVAGYNEWWGHTWNIKYPSFELSIMCLMALFKNMIWSAMDRLAPKNDWYQIFTDTATTGWQCQPEITSQIDECAGDWTMMGVWLRLEPWHGILMVPWCIMTGNPWMKGKWQWRKGIDWAARQAAHNFSWNTCGYGFAGKCNRKIQIVYTYITLESSDMWPCRLPDDYKQPPKSQKVWCGQEFGAHVVMMGCTTDCFCPNTNRTEHAWKDGYWVDDQPKQVSCWQGDNEFHIDWRLRKKYDVMLSICRVTPYVHDPCFAHMIPYSKAENGMVWWCVWVGCNIHVVYHWTWWKWWMPDIDVHEYPRDYIFLRHAGTHMYRDWSTAWEFTSDWWSDDDILYPTCPLSYHRKATWQAQKQVISDYEKEMNSIGRIVVYFIFEFHFAIQMPRHKTVINHSMTHSALQYKDEDRSHKVEKLQDDDRFIKIAKTESGAEKEKCEKLLLILDDHQYCQFSGSKQFFINEGRCEGRMNTATIHPAKWCKQIQVHQLKKGGHALIVKWPHWTKIMWWKYQAFPATSYICGGMSKQVWCRSWTGLHPRPYPRALVKFGTVASPNSVMATYKWMTWYGDWNESRVYFNSDAMSQYAEPQDSPPMCSSSKRIALYNGFQQEMCAQMCEVEHTKYQEDVPKDNPSSYWMQELRFGGAHDYHACEDTQTNWNECRNDDTWKGTIAAIRWVKAGQWIDVAAYLCSCQMTAWESPGICHFWWPKRHFSKNGYDVNSVIHSMALKPLGMAECFEIMRQRSNHTVCKTFTVHFVLMRKDWRDKMLLCAQL'
#testInput= testInput.replace('T','U')
def findCodons(aminoAcid):
        counter=0
        n_codons=1
        for codon, amino in codonTable.items():
            if amino == aminoAcid:                
                counter=counter+1
        if counter==0:
                counter=1
        
        n_codons=n_codons*counter   
        return n_codons;
        

for i in range(0,len(testInput)):
   aminoAcid= testInput[i:i+1]
   print(aminoAcid)
   numCodons=findCodons(aminoAcid)
   print(numCodons)
   totalCodons=totalCodons*numCodons
print(totalCodons)
totalCodons=totalCodons*3
print(totalCodons)
mod=totalCodons % 1000000
print(mod);